version: '3.8'

services:
  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - ARTIFACTORY_HOME=/var/opt/jfrog/artifactory
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
      - artifactory_logs:/var/opt/jfrog/artifactory/logs
    restart: unless-stopped

volumes:
  artifactory_data:
  artifactory_logs: 