name: Setup AWS Infrastructure

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'terraform/**'

jobs:
  setup-infrastructure:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Generate SSH key
      run: |
        ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
        mkdir -p ~/.ssh
        cp ~/.ssh/id_rsa.pub ~/.ssh/id_rsa.pub
        echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/id_rsa.pub

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve tfplan

    - name: Get Infrastructure Outputs
      working-directory: ./terraform
      run: |
        echo "PUBLIC_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV
        echo "INSTANCE_ID=$(terraform output -raw instance_id)" >> $GITHUB_ENV

    - name: Update GitHub Secrets
      run: |
        echo "Infrastructure created successfully!"
        echo "Public IP: ${{ env.PUBLIC_IP }}"
        echo "Instance ID: ${{ env.INSTANCE_ID }}"
        echo ""
        echo "Please update these GitHub secrets:"
        echo "AWS_EC2_HOST: ${{ env.PUBLIC_IP }}"
        echo "AWS_EC2_USER: ec2-user"
        echo "AWS_EC2_SSH_KEY: (use the private key from ~/.ssh/id_rsa)" 