name: Setup AWS Infrastructure

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'terraform/**'

jobs:
  setup-infrastructure:
    runs-on: ubuntu-latest
    environment: Dev

    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Get Infrastructure Outputs
        working-directory: ./terraform
        id: tf-outputs
        run: |
          echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
          echo "instance_id=$(terraform output -raw instance_id)" >> $GITHUB_OUTPUT
          echo "private_key=$(terraform output -raw private_key_pem)" >> $GITHUB_OUTPUT

      - name: Update GitHub Secrets Guide
        run: |
          echo "Infrastructure created successfully!"
          echo "Public IP: ${{ steps.tf-outputs.outputs.public_ip }}"
          echo "Instance ID: ${{ steps.tf-outputs.outputs.instance_id }}"
          echo ""
          echo "Please update these GitHub secrets:"
          echo "AWS_EC2_HOST: ${{ steps.tf-outputs.outputs.public_ip }}"
          echo "AWS_EC2_USER: ec2-user"
          echo "AWS_EC2_SSH_KEY: (copy the content below and add it to the AWS_EC2_SSH_KEY secret)"
          echo ""
          echo "=== PRIVATE KEY CONTENT (FOR GITHUB SECRET) ==="
          echo "${{ steps.tf-outputs.outputs.private_key }}"
          echo "=== END PRIVATE KEY CONTENT ==="